name: Prepare next release ğŸš€

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Run release draft to extract labels â˜•ï¸
    runs-on: ubuntu-latest
    steps:
      - name: Run release draft to extract labels â˜•ï¸
        uses: tchoupinax/repo-config/shared-actions/dx/prepare-draft-release@019d3c58a09a0bc8f52cde9807740ce8e3cf39d7
        with:
          appId: ${{ secrets.DEPLOY_APP_ID }}
          privateKey: ${{ secrets.DEPLOY_APP_KEY }}
